# Kitty config with transparency
    font_family FiraCode Nerd Font
    font_size 18.0
    
    # Transparency
    background_opacity 0.9

    window_padding_width 20
    
    # Mouse
    mouse_hide_wait 3.0
    url_color #0087bd
    url_style curly
    
    # Performance
    repaint_delay 10
    sync_to_monitor yes
    
    # Terminal bell
    enable_audio_bell no
